### ISSUE TITLE
XML reports supported?

### ISSUE THREAD

**Issue by marscher** [coagulant/coveralls-python#100]
I'm converting the binary format to xml first to edit the source location pointing to the working copy (the coverage report is created in an Anaconda python environment and is therefore in the wrong spot). I'm pretty sure that paths are correct.
However I get an empty result on coveralls.io. So my question is, if xml is supported at all.

**Comment by coagulant** [comment]
XML reports are not supported, coveralls generates json out of coverage binary format and can merge json (experimental feature).

I suggest looking if coverage can tweak paths on upstream side.

**Comment by marscher** [comment]
Thank you for the quick reply! I will look it up.
