### ISSUE TITLE
New maintainer required

### ISSUE THREAD

**Issue by coagulant** [coagulant/coveralls-python#122]
I'm not using coveralls myself anymore, but I'm willing to transfer rights to maintain this project into capable hands.

Until new maintainer is found, no pull requests are expected to be merged, and no releases.

// cc @jessamynsmith

**Comment by TheKevJames** [comment]
Trying to debug an issue with my usage of this project today (end result: error was on my side, but changing some error handling in coveralls-python would have led to a nicer debugging experience) led me to this issue.

I've been using this personally for a long time and am very grateful for the work you've done. I'd be more than happy to take on maintenance of this project if it means keeping it alive -- that said, I haven't contributed to this project at all yet, so a member of your community might be better served in taking this over.

**Comment by goanpeca** [comment]
@coagulant thanks for the work. I could also help :-)

**Comment by goanpeca** [comment]
Any updates on a maintainer?

**Comment by TheKevJames** [comment]
@coagulant Looks like there's been no progress on this or any issues/pulls/etc on this repo. Both myself and @goanpeca have offered to help out -- what do you think about transferring rights to one of us? I'd hate to see a useful project like this get abandoned.

**Comment by coagulant** [comment]
Sorry for the delay, I've given you both collab permissions for this repo.
I also need your PyPI accounts to grant release permissions too.

**Comment by goanpeca** [comment]
@coagulant my pypi credentials are the same (goanpeca)

@TheKevJames want to have a chat to see how we can move forward?

@coagulant is there anything in particular you would like to talk about this project? If you have no time (or no interest :-p) its fine, just checking

**Comment by TheKevJames** [comment]
@coagulant my pypi credentials are also the same (thekevjames)

@goanpeca for sure! Send me an email to KevinJames@thekev.in

**Comment by coagulant** [comment]
I've given access to PyPI. Contact me if you need any further help
