### ISSUE TITLE
Remove extra dependencies to speed up installation

### ISSUE THREAD

**Issue by Bouke** [coagulant/coveralls-python#34]
## Installation takes ~10 seconds per build

Due to all coverall-python's dependencies, installation takes around 10 seconds. Probably most of that time is spend on compiling PyYAML, only for parsing a config file most users will not be using. Also installing `requests` (great lib!) for doing a [single post](https://github.com/coagulant/coveralls-python/blob/master/coveralls/api.py#L82) only, seems somewhat overkill. Reducing the external dependencies allows for a faster install, and speeds up all builds.

    $ time pip install coveralls
    Downloading/unpacking coveralls
      Downloading coveralls-0.3.zip
      Running setup.py egg_info for package coveralls
    Downloading/unpacking PyYAML>=3.10 (from coveralls)
      Downloading PyYAML-3.10.tar.gz (241kB): 241kB downloaded
      Running setup.py egg_info for package PyYAML
    Downloading/unpacking docopt>=0.6.1 (from coveralls)
      Downloading docopt-0.6.1.tar.gz
      Running setup.py egg_info for package docopt
    Downloading/unpacking coverage>=3.6 (from coveralls)
      Downloading coverage-3.7.tar.gz (283kB): 283kB downloaded
      Running setup.py egg_info for package coverage
        warning: no previously-included files matching '*.pyc' found anywhere in distribution
    Downloading/unpacking requests>=1.0.0 (from coveralls)
      Downloading requests-2.0.1.tar.gz (412kB): 412kB downloaded
      Running setup.py egg_info for package requests
    Downloading/unpacking sh>=1.08 (from coveralls)
      Downloading sh-1.09.tar.gz
      Running setup.py egg_info for package sh
    Installing collected packages: coveralls, PyYAML, docopt, coverage, requests, sh
      Running setup.py install for coveralls
        Installing coveralls script to /home/travis/virtualenv/python2.6/bin
      Running setup.py install for PyYAML
        checking if libyaml is compilable
        gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c build/temp.linux-x86_64-2.6/check_libyaml.c -o build/temp.linux-x86_64-2.6/check_libyaml.o
        checking if libyaml is linkable
        gcc -pthread build/temp.linux-x86_64-2.6/check_libyaml.o -lyaml -o build/temp.linux-x86_64-2.6/check_libyaml
        building '_yaml' extension
        (...)
      Running setup.py install for docopt
      Running setup.py install for coverage
        building 'coverage.tracer' extension
        gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c coverage/tracer.c -o build/temp.linux-x86_64-2.6/coverage/tracer.o
        gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions build/temp.linux-x86_64-2.6/coverage/tracer.o -o build/lib.linux-x86_64-2.6/coverage/tracer.so
        warning: no previously-included files matching '*.pyc' found anywhere in distribution
        Installing coverage2 script to /home/travis/virtualenv/python2.6/bin
        Installing coverage-2.6 script to /home/travis/virtualenv/python2.6/bin
        Installing coverage script to /home/travis/virtualenv/python2.6/bin
      Running setup.py install for requests
      Running setup.py install for sh
    Successfully installed coveralls PyYAML docopt coverage requests sh
    Cleaning up...
    real    0m10.539s
    user    0m8.336s
    sys 0m0.781s

Using `--use-mirrors`, the result is only worse:

    $ time pip install coveralls --use-mirrors
    real	1m44.662s
    user	0m10.684s
    sys	0m1.183s

**Comment by coagulant** [comment]
Pyyaml is optional dependency since 1.0a, to be installed via coveralls[yaml].
For docopt and requests, I guess they don't take much time to download.

**Comment by coagulant** [comment]
Closing as fixed (since 1.0a1). Removing requests or docopt does not seem to worth the effort.
