### ISSUE TITLE
Fix coverage submit

### ISSUE THREAD

**Issue by jbmartin** [coagulant/coveralls-python#43]
Not sure if this is a coveralls.io or coveralls-python issue, but [on Travis](https://travis-ci.org/NYUCCL/psiTurk/builds/20998247) everything seems to submit correctly (see below), yet on coveralls.io the [commit coverage shows a questionmark](http://coveralls.io/r/NYUCCL/psiTurk?branch=dev). 

```bash
==
Reporting 17 files
==
psiturk/__init__.py - 1/2
psiturk/__main__.py - 0/5
psiturk/amt_services.py - 0/504
psiturk/command_line.py - 0/67
psiturk/counter.py - 0/195
psiturk/db.py - 13/24
psiturk/experiment.py - 120/528
psiturk/experiment_errors.py - 12/44
psiturk/experiment_server.py - 0/65
psiturk/experiment_server_controller.py - 0/147
psiturk/models.py - 39/102
psiturk/psiturk_config.py - 22/61
psiturk/psiturk_org_services.py - 0/118
psiturk/psiturk_shell.py - 0/1430
psiturk/setup_example.py - 0/33
psiturk/user_utils.py - 18/52
psiturk/version.py - 1/2
Coverage submitted!
Job #39.1
https://coveralls.io/jobs/1412415
{u'url': u'https://coveralls.io/jobs/1412415', u'message': u'Job #39.1'}
Done. Your build exited with 0.
```

**Comment by coagulant** [comment]
I'm closing this, considering it's coveralls.io temporary problems.
Please reopen if you think this is coveralls-python bug.
Please refer to https://github.com/coagulant/coveralls-python#troubleshooting first to obtain some info to work with.

Summary:

jbmartin experienced problem with data not displaying on coveralls.io
spectras opened issue https://github.com/lemurheavy/coveralls-public/issues/418 (no response from coveralls team)
cdeil contacted coveralls support via web form, but no concrete response was given
