### ISSUE TITLE
Token does not appear to be sent to Coveralls

### ISSUE THREAD

**Issue by leebrooks0** [coagulant/coveralls-python#54]
Hi

Thanks for your client library that makes it super easy for us to use python with coveralls.

Unfortunately I am not able the final step of sending coverage data to coveralls to work.
I reported this issue at https://github.com/lemurheavy/coveralls-public/issues/449.

Coveralls suggested that my repo token isn't getting sent? I am using Codeship and am using a COVERALLS_REPO_TOKEN env variable. I do not have a .coveralls.yml file as I am using an env variable.

Am I doing something wrong?

**Comment by coagulant** [comment]
Coveralls-python won't let you send payload without token.

To be 100% sure, could you please comment out this line in coveralls:
https://github.com/coagulant/coveralls-python/blob/ae33999902ec9410920c956f1d5ccbb1dd00f42b/coveralls/api.py#L106
And run `coveralls debug` - it will output full json sent to coveralls.io
Simply running coveralls debug won't help, as repo_token is not logged for extra security ;)
