### ISSUE TITLE
LICENSE not included in source package

### ISSUE THREAD

**Issue by joachimmetz** [coagulant/coveralls-python#55]
When running ./setup.py sdist the LICENSE file is not included. I opt to add it to MANIFEST.in.

**Comment by joachimmetz** [comment]
And please rename LICENCE to LICENSE.

**Comment by coagulant** [comment]
Please, make a pull request.

**Comment by joachimmetz** [comment]
You could have fixed this while you were typing your response. For reasons I cannot send you a pull request on short notice.

**Comment by coagulant** [comment]
Fixed in 1.0a1 release.

**Comment by joachimmetz** [comment]
Thanks, I did not got around sending you a pull request earlier.
