### ISSUE TITLE
debug + output complains about token

### ISSUE THREAD

**Issue by cancan101** [coagulant/coveralls-python#71]
I am running with debug and output and yet `coveralls` complains:
```
coveralls debug --output=asdf
Missing .coveralls.yml file. Using only env variables.
You have to provide either repo_token in .coveralls.yml, or launch via Travis
```

If I set the `COVERALLS_REPO_TOKEN` env, the command works.

**Comment by jessamynsmith** [comment]
Which version of the package? I believe that is fixed in alpha:
coveralls==1.0a2

**Comment by cancan101** [comment]
Confirmed
