### ISSUE TITLE
Coveralls and Tox 2.0

### ISSUE THREAD

**Issue by storax** [coagulant/coveralls-python#73]
I just found out today, that with the new tox release (https://testrun.org/tox/latest/changelog.html#id1), coveralls stops working on travis.
The reason is that tox 2.0 has environment isolation. You have to pass
the ``TRAVIS`` and ``TRAVIS_JOB_ID`` and probably ``TRAVIS_BRANCH`` envvar in you tox settings or coveralls will think it is not on travis: https://testrun.org/tox/latest/example/basic.html#passing-down-environment-variables.

You can see my log on travis (scroll to the bottom): https://travis-ci.org/Pytwitcher/pytwitcherapi/jobs/62437830

The error message has become confusing, because of the tox update. My suggestion is to give a hint in the error message and state it in the documentation.

**Comment by robvdl** [comment]
I have been having the same issue for the last 24 hours when I noticed coveralls stopped updating, though it's doing it on Tox 1.9.2 as well as 2.0.1.

It suddenly stopped sending the coverage report on Tox 1.9.2 about 24 hours ago, I tried to upgrade to Tox 2.0.1, then back to 1.9.2 again and both versions are doing it now.

You have to provide either repo_token in .coveralls.yml, or launch via Travis

(but this is a public github repo)

**Comment by storax** [comment]
Here is the commit that fixed it for me. 
I don't know how you set up your Tox. Pass all three environment variables to the toxenv that does the coveralls stuff. Hope it helps. I think it must be Tox. Version 2.0 was released today and yesterday with 1.9 it worked. And it makes sense when looking at the source of this package.

**Comment by coagulant** [comment]
Fixed in 78c32393194ee499f380905a3919b0810c0eed4e
