### ISSUE TITLE
How do I use coverage/coveralls with py.test?

### ISSUE THREAD

**Issue by avinassh** [coagulant/coveralls-python#77]
I can't seem to figure out how to run py.test with coverage. earlier I was doing:

      coverage run --source=myreponame setup.py test

so, I thought replacing `setup.py` with py.test would work, but unfortunately I think it's not that simple.

**Comment by lillian-lemmer** [comment]
Here's my `.travis.yml` file, it shows you how you'd use coveralls with py.test. Notably, you need the pytest-cov package.

https://gist.github.com/lillian-lemmer/0a6aaa187318152fe5ee

I also recommend installing `pytest-pep8':

` py.test tests --doctest-modules --pep8 -v --cov-report term-missing --cov=directory`

**Comment by coagulant** [comment]
@lillian-lemmer is correct. Please consult [pytest-cov readme](https://pypi.python.org/pypi/pytest-cov) for addition info.

**Comment by avinassh** [comment]
Thanks guys :smile:
