### ISSUE TITLE
Missing data on coveralls.io

### ISSUE THREAD

**Issue by alvinwan** [coagulant/coveralls-python#78]
Coveralls.io doesn't show any data, although `coveralls debug` shows that everything is fine:

Travis: https://travis-ci.org/Cal-CS-61A-Staff/ok/jobs/71158874

Coveralls: https://coveralls.io/jobs/7122833

Am I doing something wrong? Coveralls-python has previously worked. I tried deleting and reactivating the coveralls account but to no avail.

[travis.yml](https://github.com/Cal-CS-61A-Staff/ok/blob/cleanup/soumya/tests/.travis.yml)
[.coveragerc](https://github.com/Cal-CS-61A-Staff/ok/blob/cleanup/soumya/tests/.coveragerc)

**Update**: Running locally also yields the same error, and the odd thing is that this issue (beginning 7/13) cropped up a day after the [last change to travis](https://github.com/Cal-CS-61A-Staff/ok/commits/cleanup/soumya/tests/.travis.yml)(7/12). .coveragerc wasn't added until [after the issue started](https://github.com/Cal-CS-61A-Staff/ok/commits/cleanup/soumya/tests/.coveragerc) -- today, as of the time of this writing. (7/15)

**Comment by jgosmann** [comment]
I'm having exactly the same problem.

**Comment by alvinwan** [comment]
Resolved itself.
