### ISSUE TITLE
Problems with configuration travis and tox

### ISSUE THREAD

**Issue by Sinkler** [coagulant/coveralls-python#80]
I have the configuration: 

- [.travis.yml](https://github.com/Sinkler/django-radiogrid/blob/master/.travis.yml)
- [tox.ini](https://github.com/Sinkler/django-radiogrid/blob/master/tox.ini)
- [.coveragerc](https://github.com/Sinkler/django-radiogrid/blob/master/.coveragerc)

Builds in travis don't  show errors ([sample](https://travis-ci.org/Sinkler/django-radiogrid/builds/72795140)), but in coveralls i see "[0% covered](https://coveralls.io/github/Sinkler/django-radiogrid)". 

[Coveralls debug](https://gist.github.com/Sinkler/c3505fcfbfa8e299c217).

Where did i make an error?

**Comment by coagulant** [comment]
Usually it's coveralls.io problem, try asking them.
Your debug output seems valid.

**Comment by Sinkler** [comment]
thanks, the issue placed here https://github.com/lemurheavy/coveralls-public/issues/583
