### ISSUE TITLE
You have to provide either repo_token in .coveralls.yml, or launch via Travis

### ISSUE THREAD

**Issue by ionelmc** [coagulant/coveralls-python#90]
I get that here: https://travis-ci.org/ionelmc/python-hunter/jobs/81493516#L286

Anything obvious that I'm doing wrong there?

**Comment by coagulant** [comment]
I guess you need to pass Travis env variables into tox
```
passenv = TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH
```
or simply `passenv = *` (I guess it should work too)

See:
https://github.com/coagulant/coveralls-python#usage-tox--v20
