### ISSUE TITLE
InsecurePlatformWarning

### ISSUE THREAD

**Issue by jaapz** [coagulant/coveralls-python#98]
Coveralls outputs this warning message in our py2.6 and 2.7 environments (don't know about py3, but might happen there too).

```
InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

I think this is solved by upgrading to `requests[security]`.

It might also be a good idea to upgrade requests to the newest version (2.8.1) as a number of security fixes have been released.

**Comment by coagulant** [comment]
Coveralls uses whichever requests library version you wish to use to avoid dependency conflicts.
I encourage you to upgrade your python version to latest 2.7.X to ensure SSLContext is available.
